language: node_js
node_js:
- '6'
before_script:
- npm run build
deploy:
  provider: npm
  email: i@vilic.info
  api_key:
    secure: eKLPSiXe9keIuW/yJxVtQy41gV3qk4IBqrFKaaebM8m+CZsdVwbSm8bvEOATKfgb56aQLxIO4l+FLZw3E5R16qK5mXCEYioiIcsN/sa5Ov4jjG1ANim4WehEAn14Rtz+eMOZ302SBaZ1ek8rjyVnPMKrSn0SWqpG3CwGO7uB6X5+yHpJREmjQEkSZnQzei3mAZGMRe4faY+ahyi3d4jB6HwPvK71lUN8lCk9wpQrPIIxeyjJQfUBSClxvUzsO3cgj5thrOt0ZIChwn7aqjl1iWSkdV7sod9Cr1T7pwi3iolmWJFTM4WLZynPtwhJlSIDd/TxAwUx4TSVfIFMDKcyofqF//bqMd4FtHi4GkrMqBR1CFSju8y1jKoLVZNYT5ipDnI6YFYF23nq6hiImBBX0tPqhWNxu5vja29YqxyHgnkamKZlTFoLUoJHwtJen/z7NLdqwBQK/4SwTdRscHlsQoqjNQ0STnsH1eCy9YWmSoCGCXgWOzzwPC4Hy/TIUG6HhnnQVsLV3V/XdJF+Zi3zBNnAndfRvBL2kRp0woieblgFQ0Yn7/FeWv/tjMB0st0mqXKTD55UkOYngsITb4LhJttce1WLTIZUzcF2L9N8v5fKsCLc+xY/j7NtRZXQ1mJ2IaAprYT0k3f4dM0rONmxf8SSCwR+ZgvdJ04vlZEIi2E=
  on:
    tags: true
    node: '6'
  skip_cleanup: true
