language: node_js
node_js:
- '6'
before_script:
- npm run build
deploy:
  provider: npm
  email: i@vilic.info
  api_key:
    secure: bkQN3YlJ9TgUaMU/Ufah6GgjM3PD2CipXgJG6BgXhvP7xYrf66w1818DuYOzJzEHE5ShqP7OxkivemIfduRVYQbV1RszPTyTPy1dQ1tDnhH4+9MbkqSjN53t4eKSJyLxnojZhwLvQgPmFNPpQSFUdssc/ojGpUQStjeSNmj7nuh2dssPnXouqvE4J1dt7lbseyOy26whVrfKJpHVusnpq21QS9bp/f1OKvdG+O3pCASR2YteqJZDveM9SqMV8qLAnTllF0kdlC8bRwf34IojKFx0P5ZE39bRerPjQGYqkMyZYZDLd1JurVDjfaNSrcTjGic66dJOKkQ6B1PWlSz7G53a+mr4JhE74aMpu7yPam9t6kjqX2/6Jc/a8MvHl6ZW1DLb2beUJtjhPAbZvF4VMuLmZU/GhUEmaTVHN396m36PiziL3jsyDaGsSljGcf5rchQJ4dNxVM0j0aTKD/5cuZZbvNyXJLAG9FXBPiqopYP2CHFFWUh2XV/zj6PLcwN+/xgvFnrfQeVG03CfT+9RZFawWgHAIa2MgVUkxTKrht3rV3N185hvI1E/IKx/c1NQN9DghDgoUi/FelV8lfO7jKPm98o3aFhX5Uhm1X9ZM+WiLyEAR30sfqfXx6ECTKvlOdjV/IynHMmZswWO2R52q/+HknJup8ZA+8uql76Lc30=
  on:
    tags: true
    node: '6'
  skip_cleanup: true
